### ISSUE TITLE
Improve `nbictl --help` output

### ISSUE THREAD

**Issue by MLNW** [aalyria/api#50]
After building `nbictl` via Bazel (which is undocumented) and configuring the CLI to connect to our instance I wanted to see what else it does without consulting the repository:

```console
❯ nbictl --help
Usage of nbictl:
```

Apparently nothing. For other commands it does provide some usage information:

```console
❯ nbictl list --help
Usage of nbictl list:
  -context string
        name of context you want to use
  -type string
        [REQUIRED] type of entities you want to query. list of possible types: [PLATFORM_DEFINITION PROPAGATION_WEATHER TRANSCEIVER_LINK_REPORT COMPUTED_MOTION INTERFERENCE_CONSTRAINT MOTION_DEFINITION INTERFACE_LINK_REPORT SERVICE_REQUEST DRAIN_PROVISION INTENT NETWORK_NODE CDPI_STREAM_INFO SURFACE_REGION DEVICES_IN_REGION STATION_SET NETWORK_STATS_REPORT ANTENNA_PATTERN BAND_PROFILE]
```

**Comment by dgnemo** [comment]
Hi Lucas, 

Thanks for opening this feature request.
The current release was cut just before we implemented a more exhaustive `--help`.
We will soon publish a new release with the added `--help` output, and I will reply on this issue to let you know when it's available.

Thanks,
- Diego

**Comment by dgnemo** [comment]
_Sorry for the delay, we had to wait until the branch containing the change was deployed to all customers._

The new release of `nbictl` adopts a new CLI framework (improved flags supports) and more comprehensive `--help` output.

You can find the new release here: https://github.com/aalyria/api/releases/tag/v6.35.1693936218-SHA-2608c13
